defaults:
  - task_config_base
  - measurements:
    - distance_to_goal
    - distance_to_goal_reward
    - dtg_collsion_agent_nav_reward
    - success 
    - did_multi_agents_collide 
    - num_steps 
    - top_down_map
    - spl
    - psc
    - stl
    - human_future_trajectory # for falcon
  - lab_sensors:
    - localization_sensor 
    - human_num_sensor # for falcon
    - oracle_humanoid_future_trajectory # for falcon
  - _self_

type: MultiAgentPointNavTask-v0
end_on_success: True
reward_measure: "dtg_collsion_agent_nav_reward"
success_measure: "success"
success_reward: 10.0
slack_reward: -0.002
goal_sensor_uuid: pointgoal_with_gps_compass
measurements:
  dtg_collsion_agent_nav_reward:
    type: DTGCollisionAgentNavReward
    collide_human_penalty: -20.0