defaults:
  - task_config_base
  - measurements:
    - distance_to_goal
    # - min_distance_to_goal_reward
    - distance_to_goal_reward
    - dtg_collsion_agent_nav_reward
    # - min_dtg_collsion_agent_nav_reward
    - dtgof_collsion_agent_nav_reward
    - dtgf_collsion_agent_nav_reward
    - did_multi_agents_collide
    - human_collision_check
    - human_collision_count
    - true_success
    - self_stop_success
    - success 
    - num_steps 
    - top_down_map
    - spl
    - psc
    - stl
    - human_future_trajectory # for falcon
  - lab_sensors:
    - localization_sensor 
    - human_num_sensor # for falcon
    - oracle_humanoid_future_trajectory # for falcon
  - _self_

type: MultiAgentPointNavTask-v0
end_on_success: True
reward_measure: "dtgof_collsion_agent_nav_reward"
success_measure: "success"
success_reward: 10.0
slack_reward: -0.002
goal_sensor_uuid: pointgoal_with_gps_compass
# measurements:
#   min_dtg_collsion_agent_nav_reward:
#     type: MinDTGCollisionAgentNavReward
#     collide_human_penalty: -20.0